### PR TITLE
2024.5.0 merge

### PR DESCRIPTION
**Pull request by giovanniborella**
Update our branch with stuff from mapcentia

- [x] Buildable
- [x] BUG: filter icon is missing @GunnarJulJensen 
- [ ] Tested

### CODE REVIEW

**Review by GunnarJulJensen — APPROVED** [review]

**Comment by giovanniborella** [comment]
does the checkbox mean the bug is fixed? if so commit the change to this PR @GunnarJulJensen

**Comment by GunnarJulJensen** [comment]
> does the checkbox mean the bug is fixed? if so commit the change to this PR @GunnarJulJensen



> does the checkbox mean the bug is fixed? if so commit the change to this PR @GunnarJulJensen

**Comment by GunnarJulJensen** [comment]
The display filter icon on the layer property is fixed

**Comment by giovanniborella** [comment]
This is really odd..

billede

When setting a filter on "Kommuner" icon appears on "Kommuner (høj)" and "Kommuner (mellem)" are we doing some wierd name stuff?

**Comment by GunnarJulJensen** [comment]
It is name stuff….
This the logic in SwitchLayer.js method enableCheckBoxesOnChildren:

   // Set has-filter visibility
        if (activeFilters.length > 0) {
            $(`[data-gc2-layer-key^="${layerKey}"]`).find('.js-tiles-has-filter').show();
        }else {
            $(`[data-gc2-layer-key^="${layerKey}"]`).find('.js-tiles-has-filter').hide();
        }

Not very readable. But layers with a __key__ that extends the layeKey is selected as well.
The solution is properly to add a period after ${layerKey}"]`) because is separates the geometry column.
Properly an old bug

Which tenant is this ?



Fra: René Giovanni Borella ***@***.***>
Sendt: 27. maj 2024 20:38
Til: geopartner/vidi ***@***.***>
Cc: Gunnar Jul Jensen ***@***.***>; Mention ***@***.***>
Emne: Re: [geopartner/vidi] 2024.5.0 merge (PR #39)


This is really odd..

billede.png (view on web)<https://email.centerasecurity.com/url?l=503a8e961c5811efbd07005056a8faa9mx6.ce&k=22&h=df9200aa8fed18ced8fbff5a445d33ff&url=https%3A%2F%2Fgithub.com%2Fgeopartner%2Fvidi%2Fassets%2F18160930%2F0ce08f45-f428-463d-9435-b5e64a1d5045>

When setting a filter on "Kommuner" icon appears on "Kommuner (høj)" and "Kommuner (mellem)" are we doing some weird name stuff?

**Pull request merged**
